### PR TITLE
Make debugging release executables easier

### PR DESCRIPTION
**Pull request by sambrightman**
For release builds:

* build the executable with debug symbols (but leave optimisation on)
* split out the debug symbols for later use
* strip the executable

It seems that the current status of this on LDC 1.0.x is that
debugging (demangling, line numbers, locals) works for LLVM 3.7.x
only (possibly earlier) on GDB. LLDB struggles even with
demangling. LDC 1.1.x is set to improve this situation, and should
work with 3.8.x and 3.9.x-built binaries, at least under GDB.

Currently LDC binary releases are built using 3.8 and 3.9, so by
default this PR doesn't help binary sambamba releases. However,
building sambamba using LDC 1.0.x, itself built using LLVM 3.7.x,
allows for a release binary with separated debug symbols that can be
used more conveniently. Future releases should allow further
improvements.

### CODE REVIEW

**Comment by lomereiter** [comment]
Thanks, I wasn't even aware it's possible to split debugging information out this way.

**Comment by sambrightman** [comment]
Would be great if you could try this out on your setup (especially if you are on LDC 0.17/Mac). For me it works great on Linux, if LDC 1.0.x is built with 3.7.x I get an optimised executable and can later debug core dumps or attach to running processes. On Mac I think it's working: symbols are loaded automatically by the debugger. But I haven't got around to building LDC with an old LLVM yet on Mac.

**Comment by sambrightman** [comment]
I can now confirm this works on Mac with an LDC built with LLVM 3.7.x - demangling, line numbers, code listing, locals. Used GDB 7.12 from Homebrew.

**Comment by sambrightman** [comment]
Is there something I can help with to get the Linux builds synchronised with this? I understood from your previous comment that you are having to do this by hand on your own VM. I think we can run Docker on Travis to get CentOS CI builds (and tarballs, presumably).

**Comment by lomereiter** [comment]
@sambrightman yes, you can reuse docker container from https://github.com/lomereiter/centos-ldc (`docker pull lomereiter/centos-ldc`).
I don't think Travis CI allows running multiple platforms by default. Although you could kindly ask them to enable that, most people I know simply use a second platform e.g. Circle CI, and I admit I was too lazy to set it up.

**Comment by sambrightman** [comment]
I forgot to get back to you on this. I didn't think multiple platforms would be a problem, as I've used it several times without having to do much. However, I unexpectedly wasted several hours on this because using Objective C as the languages does some kind of implicit force to Mac OS X regardless of other settings. It's worth noting that there is D support (https://docs.travis-ci.com/user/languages/d) if you ever feel that you can drop support for older libc.

You can see my build here: https://travis-ci.org/sambrightman/sambamba/builds/177409143. The next problem I encountered is that the tests fail. I didn't get time to look into this. Does your binary pass tests?

What I'd like to have is an open, flexible Docker image that can build any LLVM/LDC combination by changing a single version variable whilst still supporting old libc (I'm assuming that's a requirement for now). I don't think that would be too hard to make. Then sambamba could be built automatically from Travis, and using a compiler matrix that (passes tests and) supports debugging properly or upgrading a compiler would be trivial.

**Comment by lomereiter** [comment]
Hi Sam, thanks for setting it all up!
I just checked, and the image I referred to is indeed broken, sorry about that. I've updated my setup since then, so the new [Dockerfile](https://github.com/lomereiter/centos-ldc/blob/master/Dockerfile) starts from official `centos:6` — I didn't optimize it for size, though, it's about 2.5GB (should be rebuilt on Docker Hub shortly).
I'm getting a single CRAM-related test failure in debug builds, not sure if anyone uses this functionality, though—I'd expect quite a few bug reports.

**Comment by lomereiter** [comment]
@sambrightman the build finally fits into 2h Docker Hub limit. Compilation should work once you setup the paths:
```yaml
    - export LANG=C
    - export PATH=/opt/llvm/bin:/usr/local/bin:$PATH
    - /usr/bin/scl enable devtoolset-4 --
    - llvm-config --version
    - ldc2 --version
    - gcc --version
    - git submodule update --init
    - make sambamba-ldmd2-64
    - curl -L "https://dl.dropboxusercontent.com/u/7916095/shunit2-2.0.3.tgz" | tar zx
    - ./.run_tests.sh
    - readelf -V build/sambamba | grep 'Name:' | grep GLIBC
```

**Pull request merged**
