### PR TITLE
Adding ability to slice multiple regions at once.

### PR DESCRIPTION
**Pull request by godotgildor**
This pull request allows slice to accept multiple regions much like view.

### CODE REVIEW

**Comment by lomereiter** [comment]
Hi, thanks for the effort! 

This needs more work, unfortunately:
```bash
$ ./build/sambamba view test/issue_204.bam 2:166860000-166870000 2:166860000-166870000 -f bam |\
   samtools view -c -
258
$ ./build/sambamba slice test/issue_204.bam 2:166860000-166870000 2:166860000-166870000 |\
   samtools view -c -
[main_samview] truncated file.
```
In fact, I tried to add this feature a while ago and also ran into the same issue, so it requires some debugging :(

**Comment by godotgildor** [comment]
Sorry about that.  I ran a similar test using samtools view on a bam I had sitting around and it looked like it was working (samtools view didn't give an error and I saw reads from each slice).

Debugging your samtools fail example it looks like at the bgzip block at the boundary between the first and second slice, things get weird.  For instance, the block_len is decoded into a value on the order of 20 million and the bin, position, and qual values are also not decoding properly. 

 I've looked over the logic in copyAsIs, and it's not obvious to me why there'd be an issue, although I admit I'm not an expert in bgzip formatting.  What is interesting is that I would expect each slice to fall exactly on a bgzip block boundary now, since copyAsIs will take the first block and chomp off any reads not in the region and create a new block with those reads, then blit the blocks that fully contain reads in our region, and then take the last block, chomp off reads not in the region, and then create a new block with those reads.  Then it moves on to the new slice, starting fresh bgzip blocks.  However, we see issues in a block around the transition from slice 1 and slice 2, which may imply that while we are expected to create two distinct bgzip blocks (the re-encoded end of slice 1 and then the re-encoded beginning of slice 2), samtools is not interpreting these as two distinct blocks.

I don't suppose you have any suggestions on where to look for the underlying issue?

**Comment by lomereiter** [comment]
I don't really have any concrete ideas, but the test case I suggested, with two copies of the same region, should simplify debugging as we expect two copies of the resulting byte sequence in the output file. A hex editor would be of help to spot any missing/extra bytes on the boundary.

**Comment by lomereiter** [comment]
Sorry I totally messed it up, reverted in https://github.com/lomereiter/sambamba/commit/195d3bbc98642ba4a2109086c4f99cc1ca6990d0 - please do another PR if you fix the issue.

**Comment by godotgildor** [comment]
Looking at the binary of the output bam I believe the issue is that with my proposed changes the header is being written in front of each separate region.  Looking at the code, I'm not sure yet on what is causing this behavior and was wondering if you had any ideas?

Currently, with my proposed changes the flow is:
FetchRegions:
  WriteSamHeader
  WriteReferenceSequences
  Loop over requested regions calling writer.writeRecord, writer.flush, and copyAsIs per loop
  final stream.writeExact to write close of bam file.

I've verified that 
1. writeSamHeader is called just once
2. The header is showing up 2 times if there are 2 regions, 3 time if there are 3 regions, 4 times if there are four regions etc.

My guess is that somehow the header is being buffered in the stream somehow?  

I'll keep looking but thought you might have insight into the interplay between the BamWriter object and the underlying stream that might be useful.

**Comment by godotgildor** [comment]
Found the problem.  There is a bug in outputstream.d in the flush command.  When the item is flushed, the round robin buffer is not emptied so that the next time that it is called there may still be previous data in there.  I have a fix that appears to work, I'll provide that later today.

**Comment by lomereiter** [comment]
Thanks for the observations! I also found this bug just a few minutes ago, apparently I mistakenly assumed foreach would empty it (which would happen if it weren't random access range). A more verbose `while(!empty) { ...; popFront(); }` fixes it.

**Comment by godotgildor** [comment]
That's exactly my fix!

**Comment by godotgildor** [comment]
I just issued a pull request on the BioD fix that I have.  

Do you need me to reissue the original multi-region slice pull request?

**Comment by lomereiter** [comment]
Thanks, merged!
I guess I can just reapply your original commit now, no PR needed.

**Comment by godotgildor** [comment]
Cool, thanks!

**Comment by lomereiter** [comment]
It's in master now, I'll make a release in the next few days. Thanks again for the debugging effort!

**Comment by godotgildor** [comment]
And thanks for putting sambamba out there.  We have found it very valuable.

**Pull request merged**
